name: limit-lab-homepage
services:
  frontend:
    build:
      args:
        - RUN_NPM_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: environments/Dockerfile
    user: "node"
    tty: true
    init: true
    volumes:
      - ../../:/home/node/limit-lab-homepage
    ports:
      - 3000:3000