name: deploy-to-s3
permissions:
  contents: read
  actions: read
  pages: write
  id-token: write
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build webpage in Docker container
        run: |
          cd environments
          docker compose build frontend
          docker compose run --rm frontend bash -lc "yarn install --frozen-lockfile && yarn build"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: out/

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: out

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync built files to S3
        run: aws s3 sync out s3://${{ secrets.S3_BUCKET_NAME }} --delete
