name: deploy

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build webpage in Docker container
        run: |
          cd environments
          docker compose build frontend
          docker compose run --rm frontend bash -lc "yarn install --frozen-lockfile && yarn build"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: out
          path: out

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync built files to S3
        run: aws s3 sync out s3://${{ secrets.S3_BUCKET_NAME }} --delete
