name: terraform-prod

on:
  workflow_dispatch:
    inputs:
      plan_only:
        description: Run plan without applying changes
        default: false
        type: boolean

concurrency:
  group: terraform-prod
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-run.yaml
    with:
      environment: terraform-prod
      terraform_directory: terraform/prod
      aws_region: ap-northeast-1
      plan_only: ${{ inputs.plan_only }}
      extra_terraform_args: ${{ secrets.PROD_DEV_SUBDOMAIN_NS && format('-var=''dev_subdomain_name_servers={0}''', secrets.PROD_DEV_SUBDOMAIN_NS) || '' }}
    secrets:
      aws_role_to_assume: ${{ secrets.PROD_TERRAFORM_ROLE_ARN }}
