name: terraform-dev

on:
  workflow_dispatch:
    inputs:
      plan_only:
        description: Run plan without applying changes
        default: false
        type: boolean

concurrency:
  group: terraform-dev
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-run.yaml
    with:
      environment: terraform-dev
      terraform_directory: terraform/dev
      aws_region: ap-northeast-1
      plan_only: ${{ inputs.plan_only }}
    secrets:
      aws_role_to_assume: ${{ secrets.DEV_TERRAFORM_ROLE_ARN }}
